### ISSUE TITLE
zendframework/zend-expressive-zend* packages handled wrong

### ISSUE THREAD

**Issue by adamturcsan** [laminas/laminas-dependency-plugin#16]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.3

#### Summary

`zendframework/zend-expressive-zendviewrenderer` is changed to a wrong name `mezzio/mezzio-zendviewrenderer`. The changed name should be `mezzio/mezzio-laminasviewrenderer`

#### Current behavior

`zendframework/zend-expressive-zendviewrenderer` is changed to a wrong name `mezzio/mezzio-zendviewrenderer`.
I assume it will result in a wrong package name for any zendframework/zend-expressive-zend* packages. (like zend-expressive-zendrouter)

#### How to reproduce

Update a package which uses zendframework/zend-expressive-zendviewrenderer

#### Expected behavior

Should install mezzio/mezzio-laminasviewrenderer.

**Comment by samsonasik** [comment]
closed in favor of https://github.com/laminas/laminas-dependency-plugin/pull/17
