### ISSUE TITLE
composer update with version 1 throws AssertionError

### ISSUE THREAD

**Issue by rieschl** [laminas/laminas-dependency-plugin#23]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.0.0beta1

When using `2.0.0beta1` and issuing a `composer update` with version 1 of composer, it throws an `AssertionError`:

`PHP Fatal error:  Uncaught AssertionError: assert($rewriter instanceof DependencySolvingCapableInterface) in /mnt/e/PhpStormProjects/laminas/test-mvc-co2/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPluginDelegator.php:69`

It only occurs if the corresponding `assert.` settings in `php.ini` are active.

The execution itself works because `DependencyRewriterV1` _does_ implement the method `onPreDependenciesSolving` which `DependencySolvingCapableInterface` requires.

It seems, that adding `implements DependencySolvingCapableInterface` to `DependencyRewriterV1` solves the error.

**Comment by weierophinney** [comment]
Fixed with #24
