### ISSUE TITLE
Cannot Install With Latest Composer Version

### ISSUE THREAD

**Issue by sjackson94** [laminas/laminas-dependency-plugin#58]
### Bug Report

I am using Composer Version 2.6.5 and encounter this issue when attempting to install latest version (2.6.0):
`laminas/laminas-dependency-plugin 2.5.0 requires composer-plugin-api >=1.1.0 <2.3.0 -> found composer-plugin-api[2.6.0] but it does not match the constraint.`

|    Q        |   A
|------------ | ------
| Version(s)  | ^2.5.0

#### Current behavior

 - Error is thrown, see above.
 - Unable to install to latest versions.

#### How to reproduce

 - While using a composer version of 2.3.0 or newer, run the following command:
 - `composer require laminas/laminas-dependency-plugin:^2.5`

#### Expected behavior

 - Package installs without issue.

**Comment by froschdesign** [comment]
The question is, why do you need this plugin? It should no longer be needed.
If you really need it, then use the [LTS version of Composer (2.2.x)](https://getcomposer.org/doc/00-intro.md#system-requirements).

Duplicate of #46

**Comment by sjackson94** [comment]
Apologies, had not seen the duplicate issue.
A vendor on our site has it in their requirements. For us specifically it is not needed and can be worked around.
