### ISSUE TITLE
Installation with php8.3 and composer 2.6.6

### ISSUE THREAD

**Issue by DWE64** [laminas/laminas-dependency-plugin#59]
### Bug Report

|    Q        |   A
|------------ | ------
| laminas/laminas-dependency-plugin  | 2.6.0

#### Summary

with composer install on php8.3 with composer 2.6.6, your package Laminas-dependency-plugin is locked :

  Problem 1
    - Root composer.json requires laminas/laminas-dependency-plugin ^2.6.0 -> satisfiable by laminas/laminas-dependency-plugin[2.6.0].
    - laminas/laminas-dependency-plugin 2.6.0 requires composer-plugin-api >=1.1.0 <2.3.0 -> found composer-plugin-api[2.6.0] but it does not match the constraint.

#### How to reproduce
this is the require library in my composer.json:

"require": {
        "php": "~8.0.0 || ~8.1.0 || ~8.2.0 || ~8.3.0",
        "laminas/laminas-component-installer": "^3.4.0",
        "laminas/laminas-mvc": "^3.7.0",
        "laminas/laminas-development-mode": "^3.12.0",
        "laminas/laminas-cache-storage-adapter-apcu": "^2.5",
        "laminas/laminas-cache-storage-adapter-redis": "^2.7.0",
        "laminas/laminas-cache-storage-adapter-memory": "^2.3.0",
        "laminas/laminas-cache-storage-adapter-session": "^2.5.0",
        "laminas/laminas-json-server": "^3.9.0",
        "laminas/laminas-cli": "^1.10.0",
        "laminas/laminas-mvc-i18n": "^1.2.0",
        "laminas/laminas-mvc-plugins": "^1.2.0",
        "laminas/laminas-psr7bridge": "^1.11.0",
        "laminas/laminas-di": "^3.13.0",
        "laminas/laminas-permissions-acl": "^2.16.0",
        "laminas/laminas-dependency-plugin": "^2.6.0",
        "laminas/laminas-cache-storage-deprecated-factory": "^1.2.0",
        "laminas/laminas-servicemanager": "^3.22"
    },

#### Expected behavior
we want install laminas/laminas-dependancy-plugin at the last version with the last version of php and composer.
Tks for this resolving

**Comment by Ocramius** [comment]
This is correct: the plugin only works with `composer:2.4.*`, which is LTS.

The constraint is intentional.

**Comment by froschdesign** [comment]
@DWE64 
Do you really need this plugin `laminas-dependency-plugin` ~or `laminas-psr7bridge`~? Otherwise, remove it as it should no longer be needed.

**Comment by Xerkus** [comment]
@froschdesign `laminas-psr7bridge` is used to translate between laminas-http and psr7. It is not obsoleted.

But yes, unless used with laminas-mvc-middleware or your own psr7 compatibility needs it is probably unused dependency.

**Comment by froschdesign** [comment]
@Xerkus 
Sorry, you are correct. I mean [laminas-zendframework-bridge](https://github.com/laminas/laminas-zendframework-bridge) not the PSR7 bridge.

**Comment by DWE64** [comment]
@Ocramius 
Tks for your prompt response :).

When do you plan to upgrade to Composer version 2.6.6? Is this upgrade considered in the near future?
Thank you for your prompt response.

Best regards,

**Comment by Xerkus** [comment]
This package replaces composer dependencies for zenframework packages with dependencies for laminas counterparts. No zendframework packages support 8.0. Pretty much none of laminas packages that support 8.3 act as a replacements for zendframework packages.

You do not need this package. If you do need - it was 4 years and it is well past due to move off zendframework requires.
